INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 100000, 'Fantasía', 19.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El gran Gatsby', 'F. Scott Fitzgerald', 500000, 'Ficción', 12.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('1984', 'George Orwell', 800000, 'Ciencia Ficción', 15.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Orgullo y prejuicio', 'Jane Austen', 600000, 'Clásico', 11.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Matar a un ruiseñor', 'Harper Lee', 700000, 'Ficción', 14.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El señor de los anillos: La comunidad del anillo', 'J.R.R. Tolkien', 400000, 'Fantasía', 18.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes Saavedra', 900000, 'Clásico', 13.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 120000, 'Realismo Mágico', 17.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 500000, 'Ficción', 11.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('Los juegos del hambre', 'Suzanne Collins', 800000, 'Ciencia Ficción', 14.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El código Da Vinci', 'Dan Brown', 600000, 'Suspense', 12.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El alquimista', 'Paulo Coelho', 150000, 'Autoayuda', 9.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El nombre del viento', 'Patrick Rothfuss', 300000, 'Fantasía', 16.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 700000, 'Clásico', 10.99, '');
INSERT INTO libros (titulo, autor, ejemplares, genero, precio, foto) VALUES ('El laberinto de los espíritus', 'Carlos Ruiz Zafón', 100000, 'Misterio', 13.99, '');

INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Juan', 'Pérez', 'juanito89', 'juan.perez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('María', 'González', 'mariagonz', 'maria.gonzalez@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Carlos', 'López', 'carlosl', 'carlos.lopez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Ana', 'Rodríguez', 'anarod', 'ana.rodriguez@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Pedro', 'Martínez', 'pedritom', 'pedro.martinez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Laura', 'Sánchez', 'lauris', 'laura.sanchez@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Luis', 'Hernández', 'luish', 'luis.hernandez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Marta', 'López', 'martal', 'marta.lopez@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Daniel', 'Torres', 'danielt', 'daniel.torres@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Sofía', 'García', 'sofiag', 'sofia.garcia@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Diego', 'Ramírez', 'diegor', 'diego.ramirez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Julia', 'Fernández', 'juliaf', 'julia.fernandez@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Alejandro', 'Gómez', 'alejandrog', 'alejandro.gomez@example.com', true);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Lucía', 'Vargas', 'luciav', 'lucia.vargas@example.com', false);
INSERT INTO usuarios (nombre, apellidos, usuario, email, prestamos) VALUES ('Roberto', 'Silva', 'robertos', 'roberto.silva@example.com', true);
