INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 100000, 'Fantasía', 19.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El gran Gatsby', 'F. Scott Fitzgerald', 500000, 'Ficción', 12.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('1984', 'George Orwell', 800000, 'Ciencia Ficción', 15.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Orgullo y prejuicio', 'Jane Austen', 600000, 'Clásico', 11.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Matar a un ruiseñor', 'Harper Lee', 700000, 'Ficción', 14.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El señor de los anillos: La comunidad del anillo', 'J.R.R. Tolkien', 400000, 'Fantasía', 18.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes Saavedra', 900000, 'Clásico', 13.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 120000, 'Realismo Mágico', 17.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Crónica de una muerte anunciada', 'Gabriel García Márquez', 500000, 'Ficción', 11.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('Los juegos del hambre', 'Suzanne Collins', 800000, 'Ciencia Ficción', 14.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El código Da Vinci', 'Dan Brown', 600000, 'Suspense', 12.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El alquimista', 'Paulo Coelho', 150000, 'Autoayuda', 9.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El nombre del viento', 'Patrick Rothfuss', 300000, 'Fantasía', 16.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El retrato de Dorian Gray', 'Oscar Wilde', 700000, 'Clásico', 10.99);
INSERT INTO libros (titulo, autor, ejemplares, genero, precio) VALUES ('El laberinto de los espíritus', 'Carlos Ruiz Zafón', 100000, 'Misterio', 13.99);